spring.application.name=product-app

spring.datasource.url=jdbc:postgresql://localhost:5432/productdb
spring.datasource.username=postgres
spring.datasource.password=pass
spring.jpa.hibernate.ddl-auto=validate

# JWT Settings
productapp.app.jwtSecret=your-256-bit-secret-key-must-be-at-least-32-characters-long
spring.flyway.enabled=true
spring.jpa.show-sql=true
