spring.application.name=product-app

spring.datasource.url=jdbc:postgresql://localhost:5432/productdb
spring.datasource.username=postgres
spring.datasource.password=pass
spring.jpa.hibernate.ddl-auto=validate

# JWT Settings
productapp.app.jwtSecret=super-secret-key-for-dev
productapp.app.jwtExpirationMs=86400000
spring.flyway.enabled=true
spring.jpa.show-sql=true
